apiVersion: v1
kind: Service
metadata:
  name: perf-netcorebaseline
  namespace: default
  labels:
    app: perf-netcorebaseline
spec:
  selector:
    app: perf-netcorebaseline
  type: LoadBalancer
  ports:
  - name: http
    port: 5000
    targetPort: http
    protocol: TCP